# SPDX-FileCopyrightText: 2017 Peter Serwylo <peter@serwylo.com>
# SPDX-FileCopyrightText: 2019 Michael Pöhn <michael@poehn.at>
#
# SPDX-License-Identifier: GPL-3.0-or-later

pages:
  stage: deploy
  script:
   - mkdir public
   - cp -r badge public/
  artifacts:
    paths:
     - public
  only:
   - master

reuse:
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint
